version: '3'
services:
  api-server:
    container_name: api-server
    build: ../src
    volumes:
      - ../src:/app
    image: api-server
    tty: true
    ports:
      - "80:80"
    command: /start-reload.sh
  k6:
    image: grafana/k6:0.42.0
    volumes:
      - ../k6/src:/home/k6
      - ../k6/report:/tmp/k6
    command: run loadtest.js --vus 2 --duration 10s --out csv=/tmp/k6/report.csv
    depends_on:
      - api-server
